added a new option (-c) to check derivatives provided
git-svn-id: https://ccpforge.cse.rl.ac.uk/svn/cutest/sifdecode/trunk@310 ca3beb79-f7c6-489d-80df-314e45fd556d

diff --git a/bin/sifdecoder b/bin/sifdecoder
--- a/bin/sifdecoder
+++ b/bin/sifdecoder
@@ -6,7 +6,7 @@
 #  This version October 21st, 2015
 
 display_short_help() {
-    echo ' Use: sifdecoder [-A architecture] [-sp] [-h] [-f] [-b] [-a j]'
+    echo ' Use: sifdecoder [-A architecture] [-sp] [-h] [-c] [-f] [-b] [-a j]'
     echo '                       [-p package] [-s size] [-o j] [-m] [-st j]'
     echo '                       [-show] [-param name=value[,name=value...]]'
     echo '                       [-force] probname[.SIF]'
@@ -29,6 +29,8 @@ display_long_help() {
     echo "                   (Default: -a 2)"
     echo "          -p     : decode for a particular package"
     echo "                   1=LANCELOT, 2=BARIA, 3=CUTEst (default)"
+    echo "          -c     : check derivatives for errors using finite"
+    echo "                   differences (default: do not check)"
     echo "          -s     : rough size of problem for array initialization"
     echo "                   0=debug, 1=small, 2=medium, 3=large (default)"
     echo "          -st    : starting point vector to be used"
@@ -77,6 +79,19 @@ fi
 
 TMP="/tmp"
 
+#  the command that invokes the fortran 95 compiler
+
+FORTRAN="f95"
+
+#  compiler flags for linking
+
+FFLAGS=""
+CUDAFLAGS=""
+
+#  flags for compiling the fortran 77 problem-dependent roiutines
+
+PROBFLAGS="-c -fixed"
+
 # Obtain number of arguments
 
 let last=$#
@@ -113,6 +128,10 @@ let FORCE=0
 
 MEMCHECK=0
 
+# DERIVCHECK = 0 (do not check provided derivatives), = 1 (check them)
+
+DERIVCHECK=0
+
 #  throwback to LANCELOT days (1 = LANCELOT, 2 = BARIA, 3 = CUTEst, other = 3)
 
 let PACKAGE=3
@@ -124,28 +143,6 @@ let size=2
 #  starting point vector to be used; if st > # starting vectors, st = 1
 
 let st=1
-
-#  allow file clobbering
-
-set +C
-
-#  -------------------------------------
-#  Set architecture-dependent parameters
-#  -------------------------------------
-
-if [[ -z "$ARCH" ]]; then
-#  echo "ARCH not set"
-  if [[ -z "$MYARCH" ]]; then
-    error ' no architecture specified and environment variable MYARCH is unset.
- Either specificy architecture with -A option or set variable MYARCH.
- and re-run.'
-    exit 2
-  else
-    ARCH=${MYARCH}
-  fi
-fi
-
-eval "`cat $SIFDECODE/bin/sys/$ARCH`"
 
 #  -------------------
 #  Interpret arguments
@@ -179,6 +176,8 @@ while (( i <= last )); do
   elif [[ "$opt" == '-st' ]]; then
     (( i++ ))
     let st=${!i}
+  elif [[ "$opt" == '-c' ]]; then
+    DERIVCHECK=1
   elif [[ "$opt" == '-f' ]]; then
     let automatic=1
   elif [[ "$opt" == '-b' ]]; then
@@ -220,6 +219,28 @@ while (( i <= last )); do
   fi
   (( i++ ))
 done
+
+#  allow file clobbering
+
+set +C
+
+#  -------------------------------------
+#  Set architecture-dependent parameters
+#  -------------------------------------
+
+if [[ -z "$ARCH" ]]; then
+#  echo "ARCH not set"
+  if [[ -z "$MYARCH" ]]; then
+    error ' no architecture specified and environment variable MYARCH is unset.
+ Either specificy architecture with -A option or set variable MYARCH.
+ and re-run.'
+    exit 2
+  else
+    ARCH=${MYARCH}
+  fi
+fi
+
+eval "`cat $SIFDECODE/bin/sys/$ARCH`"
 
 #  -------------------
 #  Create problem name
@@ -381,7 +402,7 @@ fi
 
 # Define the path to the decoder
 
-DECODER=$SIFDECODE/objects/$ARCH/double/run_sifdecode
+DECODER=${SIFDECODE}/objects/${ARCH}/double/run_sifdecode
 
 if [[ ! -x $DECODER  ]]; then
     error "No SIF decoder sifdec found in
@@ -466,5 +487,47 @@ fi
 #  Record the type of derivatives used in the decoding
 
 echo $automatic $ad0 > AUTOMAT.d
+
+#  If required, check the provided derivatives are correct
+
+if [[ $DERIVCHECK == "1" ]]; then
+
+# ensure that the current test problem has been compiled
+
+  [[ -e RANGE.o ]] && $RM RANGE.o
+  [[ -e ELFUN.o ]] && $RM ELFUN.o
+  [[ -e GROUP.o ]] && $RM GROUP.o
+  [[ -e EXTER.o ]] && $RM EXTER.o
+
+  NSUB=( "ELFUN.o GROUP.o RANGE.o" )
+  [[ -s EXTER.f ]] && NSUB=( "$NSUB EXTER.o" )
+
+  for i  in  $NSUB; do
+    if [[ ! -e $i ]]; then
+      j=`basename $i .o`
+      cp ${j}.f ${j}.f90
+      $FORTRAN $PROBFLAGS ${j}.f90
+      if [[ $? != 0 ]]; then
+        exit 9
+      fi
+      $RM ${j}.f90
+    fi
+  done
+
+#  create the executable
+
+ OBJMAIN=$SIFDECODE/objects/$ARCH/double
+ ${FORTRAN} ${FFLAGS} -o check_derivs $OBJMAIN/check_derivs_main.o \
+  $NSUB -L$OBJMAIN -lsifdecode
+
+#  check the derivatives
+
+  echo " "
+  echo " Checking supplied derivatives"
+  echo " "
+
+  check_derivs
+fi
+
 exit 0
 
